name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths:
      - 'landing page/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cd "landing page" && npm install

      - name: Build and Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_LANDING }}
          working-directory: "landing page"
          vercel-args: '--prod'
